apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2018-12-06T10:59:17Z"
  name: eventlistener-deployment
  namespace: default
  resourceVersion: "177104"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/eventlistener-deployment
  uid: fa291310-f945-11e8-9486-8e0f293339d0
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: eventlistener-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 1
  desiredReplicas: 0
