apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2018-12-06T10:14:42Z"
  name: fulfillorder-deployment
  namespace: default
  resourceVersion: "172747"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/fulfillorder-deployment
  uid: bf8e66ce-f93f-11e8-9486-8e0f293339d0
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: fulfillorder-deployment
  targetCPUUtilizationPercentage: 30
status:
  currentReplicas: 0
  desiredReplicas: 0
