---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        - name: TILLER_TLS_VERIFY
          value: "1"
        - name: TILLER_TLS_ENABLE
          value: "1"
        - name: TILLER_TLS_CERTS
          value: /etc/certs
        image: gcr.io/kubernetes-helm/tiller:v2.11.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /etc/certs
          name: tiller-certs
          readOnly: true
      volumes:
      - name: tiller-certs
        secret:
          secretName: tiller-secret
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdBekNDQSt1Z0F3SUJBZ0lKQUpMR21OaHhmOGRqTUEwR0NTcUdTSWIzRFFFQkN3VUFNRjR4Q3pBSkJnTlYKQkFZVEFsVkxNUmd3RmdZRFZRUUlFdzlIYkc5MVkyVnpkR1Z5YzJocGNtVXhFekFSQmdOVkJBY1RDa05vWld4MApaVzVvWVcweER6QU5CZ05WQkFvVEJuUnBiR3hsY2pFUE1BMEdBMVVFQXhNR2RHbHNiR1Z5TUI0WERURTRNVEl3Ck5URXhNamN4T0ZvWERUTTRNVEV6TURFeE1qY3hPRm93WGpFTE1Ba0dBMVVFQmhNQ1ZVc3hHREFXQmdOVkJBZ1QKRDBkc2IzVmpaWE4wWlhKemFHbHlaVEVUTUJFR0ExVUVCeE1LUTJobGJIUmxibWhoYlRFUE1BMEdBMVVFQ2hNRwpkR2xzYkdWeU1ROHdEUVlEVlFRREV3WjBhV3hzWlhJd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3CmdnSUtBb0lDQVFDMW96SXR6MFB0cEpBZ1JuUE9oQkFrdGNtdStaMVdYcjkvYlN4OW5tYk8xanJJRkp6andYK0cKQ0FDK01wbElzY2ppbWNRVUZ3cVZEakhnTEcxVEFPYUJqRk5nZ3ZUMEk0VU9XUWdiZEE2S3RkN3k4c3VTaUNoMwpMUGpEOEFqaTJOV21oR3FlcmpCelJuZ3pmL1NHd3FQQmhMMng1Q1duN3RtTUpWMXNYWFpNUjFCUkxMcGp3T2V1CnNxU3lwdkZpTVl2T1N0SDdsN205a2JCaWtrOE9ubGxtRERNaTA3TUpSL0d3by80NStLcm5ES3NPUStMWmljaHkKVms3WVJueDd1SVA3RTY1ZHVoZW9sL3lBYmhrWTZjVzhmRWNVOU9ySUEzUzR4VmtJWTBobHZYamkwSmdES3RxVAoyaGsySmgybVNBeFNjcXBOTnNySlJCV2w1K1lwNFV2Q3ZOcXpySHdwOGMrYW1qN3M2czhLYkd0aC9ndVhGbEU0CnVxRXFRSkp2YWlnYzYvTDBSQnRYN2hHVWtXNk1PTkJITnhHSDBjYW1MUVJRSDJqL0puTTNHSmxLSDZySFlUbUcKeklqMm9WeG9mVk1kb0xwckdqSVMzTFdhTzQ2RFJXR2NrUC9kUTNPaFFqZVpNQldoNDBiUTZMelhCRC9keXFLegpXSkM1Q3BzMmlocWpTaVlaK3V5L05qK1NhcHEreGhwMklkUTJQNG9PRmFVKzVoL0czZFN3eDlUNS8rc3A5cHArCktKaEFaaVhYb1d3bFViZmoxUVdzY0dTaGtGNDVyL0lQUTFxQ1dVS2wxNkxZd09EL3pIN29jVjN3K3pPaHNHbXMKd2YxUFNPSnBRV3l5Z3kxaExXQ1FndGJCZllaUGx4NjRDb0tPcW8rdndDTExXcVlvZ3grYWx3SURBUUFCbzRIRApNSUhBTUIwR0ExVWREZ1FXQkJSc0NjV2MwZ0ErSzJQVjhvUjNUc0VHMnJrQWJEQ0JrQVlEVlIwakJJR0lNSUdGCmdCUnNDY1djMGdBK0syUFY4b1IzVHNFRzJya0FiS0ZpcEdBd1hqRUxNQWtHQTFVRUJoTUNWVXN4R0RBV0JnTlYKQkFnVEQwZHNiM1ZqWlhOMFpYSnphR2x5WlRFVE1CRUdBMVVFQnhNS1EyaGxiSFJsYm1oaGJURVBNQTBHQTFVRQpDaE1HZEdsc2JHVnlNUTh3RFFZRFZRUURFd1owYVd4c1pYS0NDUUNTeHBqWWNYL0hZekFNQmdOVkhSTUVCVEFECkFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJCQzRPZGc5OUJNNEM4OTdiZDBva1ZjWmZYZXFINnZDZ0IKK3IvVlEyUW1meEt6Yy9ienI4dWJNL3NWeTVvczRwaEJyS2dWM3ZyTnl6QldHQ2k4VlVETDlQL2g2Rnc4QXBtKwpwTjFON3dHaFRXS2dGZzUrNWxoN1dGNk5tcE1KQ2IxeEx6TzFzdWNSSDVJdk9Tb0J5djhLcUpacFZsQnlXU3ZBCldQQXdMdUprbHpxQ2JwNXk0TFB4Z2lFa3dvcEpmOWR5cTZPZ3dEN21rSW1qY1hsTWJZNjh2NmZxWTUweGlWNkoKZGZlcFF5anNBZU1EbDBxYlUvOTJDUkxZdVgvNVkydjUvbGJSRFVXUUZSNS9ycWhNZ1VFZksxcW5pS3drSHBWdQozdWJOd1QxSXBlOE10NGxocmk5S0phVUI4MVFscGx3dWE5dUVNazdwK0MxdlJESCt4bGdmNk14cGc3RFVjTjR2CkZKYlNUK2ZMajZuODNMUTZNU1FPaUp3TWRJVGl4eGxHRVVmY1VtZTdUdHhndmJ2NVNma1pMeldUYVVWNG5CRmkKT3oyUE1KQTJ4eUdZeUcyMlE3TDJuZllvU2ZBOGNPc0lKRTFObjBNS3UxQUp2QlhoZjJtTjFCd2ExYmxQNGx4Ywo2K0NkaGRwY1ZOb0V6SWF6Rml1dU1lbWhmQjZGcS83V0pKcDIwcmtpWnlvRk1UbHRBUERYVXozandQeVNNT1I3ClBGZmlaYlhvK1NhWFh5NUtwTDc2ZDBwcnJ3cUtqV0t0L1pkcmtEazVocS9Gdi9vWStPaVA1V0VKWmdoWHJZbEsKVnBvdjkxWktKVUNxeG5vS0F1bzdmZkJBTFpPNlQyL3NVcGxTSE1CWFkrTk5HK2dxYURRRzM1WlNiemVsaFMwdApjbXp5cXE5OU5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZSakNDQXk0Q0NRQ2xMc1FlQTdGWW9EQU5CZ2txaGtpRzl3MEJBUVVGQURCZU1Rc3dDUVlEVlFRR0V3SlYKU3pFWU1CWUdBMVVFQ0JNUFIyeHZkV05sYzNSbGNuTm9hWEpsTVJNd0VRWURWUVFIRXdwRGFHVnNkR1Z1YUdGdApNUTh3RFFZRFZRUUtFd1owYVd4c1pYSXhEekFOQmdOVkJBTVRCblJwYkd4bGNqQWVGdzB4T0RFeU1EVXhNVE14Ck16SmFGdzB4T1RFeU1EVXhNVE14TXpKYU1Hd3hDekFKQmdOVkJBWVRBbFZMTVJnd0ZnWURWUVFJRXc5SGJHOTEKWTJWemRHVnljMmhwY21VeEV6QVJCZ05WQkFjVENrTm9aV3gwWlc1b1lXMHhGakFVQmdOVkJBb1REVlJwYkd4bApjaUJUWlhKMlpYSXhGakFVQmdOVkJBTVREWFJwYkd4bGNpMXpaWEoyWlhJd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDOHBQRGY5N05kNEpCTGJTL3ozVzdSMUNwR2ZzNHJSU3VKSFFPM0ovZzkKeWRTMm04Y0FWYWh2cmg0MWdFMmdGUW9KZmZiQ3AvNjZ0elhYUWZlT3RoazZKVU1CLzY3UU02dHBRYXRTT01zdQpNeW94RTRUcEFhbWtRYVV4Qm9aYzVMeTMwbjRFNnhmR2RxUXg2ZzJRY252K21ZakovKzJ5Tis3K2pmdmU1R01vCkE5dzdEK0Y0d1BXa3M4cWxjWEVkeEZaRDU2aDhwZFpERU5VNHgybXArV1hlSlBxVlphYmZVdFR2NklTYldISm4Ka0NWQkFRUEJYV0JjSTJKcm1qTkRBQnBNaXY4VUlLdUg0U2wzVUpnM3pnOEZmZzhZWmZTYWNZZ21ucklXZ0g4SwpjYmFGSU5FMGQySDFQUVhUY0w0aDVETUlZVERsZ0tKTVJhOE1hK3hDSnU2N2F2aTR0djFNNWNaTldrek9ZaTNYCkR6TFBKUFVGZmZWOVliYVFUa21CcnZBZ3Q2NE13S3QvdExmeGo4WFBFaVhwMkVIQ3JCNkJwaytkZGdwaVNMcEkKSFRvTmh2QjRMcjFVaHlSclp3eHZUdTErU2JMWHJuR0JySmt0RDNyYXBON0wzYWNnbVYyTWN6bVlrL1VEdHcyVApYRW5zaHlhaGk2ZE1LbEpKM1FVVkFpbG5BbEU4UlEyaGZPUXJ1VUlubTBoQi9vRHE1a3Jha28zc0RTZ1NTSnFtCjV1ZWd6LzFPamUxMVh0SkRrdU1BbEJBZnRFTGsrRUE1NU1GZk56cHhjSXkxUGlvdUc2YzMxKzQ2d3h3UmR0ZTYKK0phUlNnMlBiQ2NlNEp6eU9Sa1NpdS8rbnZQemZKYnR4TnhhSmd0Sko2dlFyNCs2VVdEMjlVaVN0WDFiU0dLZQpmUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJCUVVBQTRJQ0FRQ1ExaWdaVTRmak04NTNqY1h3TWdBaEJrOHBqRFlWClJ5VTljM3RERVhndE1FMkhicDNEdUMxZWkvZ1Rob2JRcCt3cjAxeXZKTVBJaWo1bHJDZER5ak1RUXdiQ00veGoKTU5XdHJsblR5Znh4ZjR5aFBkUVB0bmpvMFE2VzJibjNUWmRpWGFVM081MUdhZHczQ2xxYnMwL21wdzhuY3dDdQpDemFKVzFFRjlpM3dTYWJmVHh5NWJyekJXK2tWWjFTWUFWWW9Va1UrMDdOaEJEOFMzd1NTOThRbndXRGd6WE1UCnRaVjlhNmtHZXlFSVR5UXZSbk03TXZPRmVZR0N0bWZYUWlNNXdnN2lMS2F1bW9oU1NnTkFLaDV1blJZbmFlL2sKZ1NoVE8zdlZRbWl5akRPNTVEVVVOaDdtWUNOUFBmTTVqdWp5RjNQTHFpR3N1U1lteTRxOGtXZ0dCUCtwQ2F3TQp2WUFkMGxHQjRkLzd0YXdhMmlkcGlHS2JySVZLcnY4U1JETkRRVG1hb1lqaTBHWUs2ZTVSZHlSNTVFMTk2ZFl3Clo4b3ljMHptRjl0V0FPM1ZlS3V0b1ROcUdvY0lCTjJCdWc2NnRSM2pLSHF4VXpYN3FUMUpvdTNZU0YzLzhxMXUKYjMxS1cxTEJwcUZVMlRwbis5aGlOS1BkQkQraUs3eHFoUUpzSTkzNS90SEQydjlBM0VwMHhTTDZMcDJkWUQyRQpBY2hUZ3laVmt4TzRBSnhaRFpUQjBoVWlSdEhzeklLay8rWWNFNmVQYVpFTzhaM1VReEozaHFqN1cyR0FMZ1Z4CnpPRjBFZ2preTV3WFZZSmFGbXVWUlVWVm5KWkhwT0Z6d1hsZ2Y0ZDd2L0VTa2NBcUZxV0ZReTlLMG82TmVuamcKb3JVVzNuWnFVd2VuT3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBdktUdzMvZXpYZUNRUzIwdjg5MXUwZFFxUm43T0swVXJpUjBEdHlmNFBjblV0cHZICkFGV29iNjRlTllCTm9CVUtDWDMyd3FmK3VyYzExMEgzanJZWk9pVkRBZit1MERPcmFVR3JVampMTGpNcU1ST0UKNlFHcHBFR2xNUWFHWE9TOHQ5SitCT3NYeG5ha01lb05rSEo3L3BtSXlmL3RzamZ1L28zNzN1UmpLQVBjT3cvaAplTUQxcExQS3BYRnhIY1JXUStlb2ZLWFdReERWT01kcHFmbGwzaVQ2bFdXbTMxTFU3K2lFbTFoeVo1QWxRUUVECndWMWdYQ05pYTVvelF3QWFUSXIvRkNDcmgrRXBkMUNZTjg0UEJYNFBHR1gwbW5HSUpwNnlGb0IvQ25HMmhTRFIKTkhkaDlUMEYwM0MrSWVRekNHRXc1WUNpVEVXdkRHdnNRaWJ1dTJyNHVMYjlUT1hHVFZwTXptSXQxdzh5enlUMQpCWDMxZldHMmtFNUpnYTd3SUxldURNQ3JmN1MzOFkvRnp4SWw2ZGhCd3F3ZWdhWlBuWFlLWWtpNlNCMDZEWWJ3CmVDNjlWSWNrYTJjTWIwN3Rma215MTY1eGdheVpMUTk2MnFUZXk5Mm5JSmxkakhNNW1KUDFBN2NOazF4SjdJY20Kb1l1blRDcFNTZDBGRlFJcFp3SlJQRVVOb1h6a0s3bENKNXRJUWY2QTZ1WksycEtON0Ewb0VraWFwdWJub00vOQpUbzN0ZFY3U1E1TGpBSlFRSDdSQzVQaEFPZVRCWHpjNmNYQ010VDRxTGh1bk45ZnVPc01jRVhiWHV2aVdrVW9OCmoyd25IdUNjOGprWkVvcnYvcDd6ODN5VzdjVGNXaVlMU1NlcjBLK1B1bEZnOXZWSWtyVjlXMGhpbm4wQ0F3RUEKQVFLQ0FnQUNUWUVqT3NMVndvZ0FZN1RTSlVIVkRlSDJPbFlKOFM0MjNrUE5XSStQTVllSE14K2F3WERzN0JNeQpVLzZlbGFNcHVuL29vR1Jib3lEbEg4a0YxUE01NG5xTzY3QVdtb3JkSGhBWlVOZ3FHRFhMbzVGYnhzbHJWK0hNClYyZ01lajVUZ0I1SnNSVDVOem1KNG5HSDhkM1JuYzR0cVJJZHV0RVFDbXVvck9FSS9BTVVOWDFyRysvanNzNG0KZHR3S29QcnNtVWRWUGpEL1lKVTV2RFZ0L2IxZ21OTDJQK2Rwa25sRzlHK3A5Y3B2dVRLN09HZnpWRkI0ejNYRQpHbjNGczVxZWxKUElpeDJNNnhLMmdpVlppUXBsNXNRSWFEWTBMRzZkQ2hMaWMyOFprWW5JMWoyM2hqMkw0TkxSClllN3dPdmprZ1VzM2dmcDVNK0NQSmtJY0RKMmRacStrUVFNR3NMUVE4ZmMvbjVvb2JKTEdOYWhvVHJVWmVJNW8KUnJjTWc1SHdiYS9uZjlheUVMK1gxV2VwYkJLYk5ERzhTdDdOQjcvUnhGeGFCT3pGc05KU3ZHRWJlSDVKWUxLVAp1Ti9ob0R3OFkyZ0dZQkM4a01hMkswbDJTTnBEc1NyNTc4UVhEcDNEc2hFUlZRQ2Q1c2dEWVNLREUyVWtEZGI2CnRTc001RUw5emk3ektXUzErL1l0RlMxeWZGYXRscmlLbWEwOUhHbHRUeEcwa3pNNG51TlFPa1lPM2ZPM2N4WkIKS0lVdVFsdlNXRlZOYnc0bnBJWHJPZFBja01yUFFLQ1A4Z3lISmZOUjR4TzdIUjdZZzVwY1lnTnlYMUtXenU4SQpTaVp0MndVL2VsNlI5TlFQY04wbnFxMGhPR1M2YzRQWDEvS2hoa2poa3YxcTRIalBnUUtDQVFFQTdLUS9SV0FtCk9od0pwWkZYdnlIai9DQzZTeCtqYXRZbVJWLzlqcVRzenA4OHhiSUFYSE9xMVk5RjlsZ00rZWNDOHB3UjVZZ3MKc2pnTkwyU1krVTFZTGtzVENpazU2QUZ0dGZvSXJwK21acjhmb2hzTi94L2JFUHcvTU1OdWpTNk4xd1N0NkMyZwpGaS9RMUdnWXZieTdCWktQNHZOaXpnOUtRN1RmY2JCVDFmb0hvdGZmeDhnY1VwYlNnTm5aRUJLQUkvbUhkWlNtCi9QTDUySUNqOGlkMVFrNzBUOGg5VFEveGxZQVlDUU52VHVmK21LbENSNWpZUTdhZlpFelFNY1NLK0QrcFZXTWQKL0VFNjY0Q0dEYUZPY0VoekgvcFBGWWlWMjVUSThCVXZ5UjlUSjNnZUJHM0g1QlRTL1FCKzZhYUhPM1haZUx3TgpNbUgxN0tKYSt5eGJDd0tDQVFFQXpCT0ltRDZHd2RLeWFtNG5wUWxoajN5MS9oMjIxb01maW5VRzNwUXdNcnNoCmdUenkzNno3Y3h1dkhyWFFRbm9EY04zYTBtVzVRZVp3TitPK3FXbUtUYVlvKzR4cFNMdE5pc2V3K2RUeDFHS20KY3ZzT3hxU21INjh2eWxyQ1pGQVJhRmMyNzBJNFRDS2o5bGloV2ZqZ05ocUNySTRPeFRSWC9LOHBGNUdKRXA5Wgo0SU1ydlUvMWx3MERxc3hCTEI0WnVkaml1d0RVVmhLM0tycStzQjE5eEo0VHJFWmZWSVMvREoyY2toVzMwVXAyCjBYa1I3NEZsNUdIZW9BVXZIYk9ydTd4QllQNlpFS1ZmRXovMnFKWG1vUHd6emZnL2M4QnB6L1o5WXdaeHB6alUKakphY0Q5WGNuMDhKeGpvdTMvVUVRWEpuVUN3Zk9uTjFKVmFRVmtXaGx3S0NBUUEvWlIwQ0krajV4a3NiVE4yWgorYVZQQlNHRFFKMlI0SDd1TlBJRGhkRmU1Uy90c21zQVdZaFpvQUZaSm11TGcwUzU0Kyt6Y3hDdVNlL1dVM2ZiCnljbW0xVHZyaS9IVVlwV1dtNzQ1c2RGdFV5UlJWRGdpc2RFSk10cG00T1E3OUUzUlhaS05VYlBDWGRydkhGZ00KZElRUjBScTA3UWo2TlFSck1RaHZONUt1RDBaK2JLQ3ByOFZPcHRNTDY5Q0h5cjBEWmpUUTNoc0NSc0dDSzZ4QQpFaXdLc0lZbzNZZ2IzZnFWVjNTWTdZK2pMdWw0MGxkTVFQa200c1MrcFFsZFc4N3pCSE1EeWdMZGNrZ3JrUW5ZCm11OGRpM3MwQk9XczJpTnphTitQMmMwc2J6VGlyUDQxcDRkV1pmSEVENTd3VDBtSk4yQWtSUlN2KzZoYlZYOVUKTEtUVEFvSUJBRDhJN1pFeEJ3akpYdWkyKzdIamN1b1NPRmkwcnV3VmRtR2JBak13REs4dTFBdUtXdTZ5REwwaQpXUFlnYktLTDg1SWlSTnZtSmRId0xzdGtvbGpMeTdkdVVveFljNURPb2dYeTVueFV4Um00R3ZlN0NuWmJGeUVFClNMdTFTd1FYSXpsYWJ4SjZIcytOaDUycEJMVzR4UENSUWJtdzYya0lZUUVnelkyRkc1VFArYi82WkVGR2VISmUKeDdveSt4SjRmYlBGQlV1RDF4SjdGMjZ3WGdRaUo5M2FnZk1kallhYXRqUmNYcWRVNUFGV2dkcjBEWkV3STl2bQpTeENjYVZCQVZoUlg4czNWOWt1SStSUUdGdGM5N2czZHVOYXZEbEpmcFk5aDhKcnN1NkJPVW9EV2FJQVBxK1RkClVnU1RwalR4Qm81OG11TE5yaHVzM0F0YmNKdmxTQ01DZ2dFQkFNN29LUmtHaS9OV015YXlCY3pvTEhCSk9KRE8KOUU1ZjFaa0lmZytnWU13VXh4amE3YldzaFJqU3pMOTlzdUdTSS9PNWwySEZQRXNKMEIwSzc3dGtDOUdBSlF2UworSlFIaC9TL1dnbjNMUTdCdFhSbFE3MW13alVxWkVKczgrRW9tYzdPV1ZRY3RCWEQvRVpWYjgzVXNXMDlSMEZOCkVoVXVldE5JQTJpbUxEWDBGTlpUdjlnbk8wK3pGR1N0NkF3SHNjWE1rNzlqUWpQREQ4V1dDcER3cjhlNmN3ajUKS1JqOTRjOG41a1h6cU1kaktnaXJMQ1FvTjhXMnZPQVFwT2JKNjRHUDZObWwzanVQT1ZWeTc2OXVCdVpSL3R1RApQRkUyeDhEOEVIeVhVUkxubzFOQzM2Y2pFS2tGaFNVKzJGTDFjRENlUGs5L0ZTcVpLczZ1dWg3YmU3cz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-secret
  namespace: kube-system
type: Opaque

...
